package main

import (
	"text/template"
)

type TemplateParams struct {
	CreateMap  bool
	MapName    string
	ErrorsInfo []*ErrorData
	Package    string
}

var (
	tmpl = template.Must(template.New("map").Parse(`// Code generated by error_helper; DO NOT EDIT.

package {{ .Package }}

{{if .CreateMap }}
var (
	{{ .MapName }} map[int]string
)

{{ end }}
func init() {
	{{ .MapName }} = map[int]string{
		{{ range $i, $el := .ErrorsInfo -}}
			{{ $el.Name }}: "{{ $el.Text }}",
		{{ end }}
	}
}
`))
)
